### PR TITLE
6 login

### LINKED ISSUE #6: Create login/register forms

### LINKED ISSUE #7: Create "routeguard" logic, pending backend

### LINKED ISSUE #9: Saving data to device storage/persistent login/.env
- [x] device storage
- [x] persistent login
- [x] .env

### PR DESCRIPTION
**Pull request by ryksyy**
Even tho backend connection has not yet been made I think this should be merged to main as it has major restructuring to improve readability and to get context to work properly

Also includes Santeris group page so I could get rid of some of the placeholder stuff

Expected behavior: Cannot login without typing anything. Once you log in you should be able to see the username you put down by going to the "swipe" page and pressing the button.

Using  the back button from top level screen should either take you back to your previous screen or out of the app if you were just logged in.

Reopening the app without having metro rebuild should throw you directly to group page and navigating to swipe and pressing the button should show your username that you registered when using the application before

Creating a .env file and setting BASE_URL as [ anything ] should print [ anything ] when you press the register button

Closes #6 
Closes #7
Closes #9

### CODE REVIEW

**Comment by ryksyy** [comment]
found an issue somewhere. Something is apparently imported wrong and causing a warning. Dont merge till fixed

**Comment by ryksyy** [comment]
something to do with the unfinished Styles.js as I cannot replicate the warning on commits made before that and it first appears after the file was added

**Comment by ryksyy** [comment]
fixed now, everything should be fine now

**Comment by ryksyy** [comment]
I might aswell finish the other issue I opened while at it

**Review by MarsalkkaSandels — APPROVED** [review]
yes.

run npx expo start --clear after creating .env

**Pull request merged**
